//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visio_Multi_Page_Layer_Selector.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Visio_Multi_Page_Layer_Selector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_addToSubCategory {
            get {
                object obj = ResourceManager.GetObject("img_addToSubCategory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_check {
            get {
                object obj = ResourceManager.GetObject("img_check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_coffee {
            get {
                object obj = ResourceManager.GetObject("img_coffee", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_default_exist {
            get {
                object obj = ResourceManager.GetObject("img_default_exist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_defaults {
            get {
                object obj = ResourceManager.GetObject("img_defaults", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_defaults_add {
            get {
                object obj = ResourceManager.GetObject("img_defaults_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_delete {
            get {
                object obj = ResourceManager.GetObject("img_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_favorites {
            get {
                object obj = ResourceManager.GetObject("img_favorites", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_home {
            get {
                object obj = ResourceManager.GetObject("img_home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_layers {
            get {
                object obj = ResourceManager.GetObject("img_layers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_mpls_128 {
            get {
                object obj = ResourceManager.GetObject("img_mpls_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_mpls_256 {
            get {
                object obj = ResourceManager.GetObject("img_mpls_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon img_mpls_2561 {
            get {
                object obj = ResourceManager.GetObject("img_mpls_2561", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_mpls_32 {
            get {
                object obj = ResourceManager.GetObject("img_mpls_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_mpls_512 {
            get {
                object obj = ResourceManager.GetObject("img_mpls_512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_mpls_64 {
            get {
                object obj = ResourceManager.GetObject("img_mpls_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_paypal_donate {
            get {
                object obj = ResourceManager.GetObject("img_paypal_donate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_settings {
            get {
                object obj = ResourceManager.GetObject("img_settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_subCategories {
            get {
                object obj = ResourceManager.GetObject("img_subCategories", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        internal static string loc_about {
            get {
                return ResourceManager.GetString("loc_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die active ähnelt.
        /// </summary>
        internal static string loc_active {
            get {
                return ResourceManager.GetString("loc_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die add to defaults list ähnelt.
        /// </summary>
        internal static string loc_add_to_defaults_list {
            get {
                return ResourceManager.GetString("loc_add_to_defaults_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die add to subcategory list ähnelt.
        /// </summary>
        internal static string loc_add_to_subcategory_list {
            get {
                return ResourceManager.GetString("loc_add_to_subcategory_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply layers settings from favorite ähnelt.
        /// </summary>
        internal static string loc_Apply_layers_settings_from_favorite {
            get {
                return ResourceManager.GetString("loc_Apply_layers_settings_from_favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure to delete? ähnelt.
        /// </summary>
        internal static string loc_are_you_sure_to_delete {
            get {
                return ResourceManager.GetString("loc_are_you_sure_to_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply ähnelt.
        /// </summary>
        internal static string loc_btnApply {
            get {
                return ResourceManager.GetString("loc_btnApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Buy me a coffee ähnelt.
        /// </summary>
        internal static string loc_Buy_me_a_coffee {
            get {
                return ResourceManager.GetString("loc_Buy_me_a_coffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm ähnelt.
        /// </summary>
        internal static string loc_confirm {
            get {
                return ResourceManager.GetString("loc_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die defaults ähnelt.
        /// </summary>
        internal static string loc_defaults {
            get {
                return ResourceManager.GetString("loc_defaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete entry ähnelt.
        /// </summary>
        internal static string loc_Delete_entry {
            get {
                return ResourceManager.GetString("loc_Delete_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete? ähnelt.
        /// </summary>
        internal static string loc_Do_you_really_want_to_delete {
            get {
                return ResourceManager.GetString("loc_Do_you_really_want_to_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to overwrite the favorite? ähnelt.
        /// </summary>
        internal static string loc_Do_you_want_to_overwrite_the_favorite {
            get {
                return ResourceManager.GetString("loc_Do_you_want_to_overwrite_the_favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter the name under which the favorite should be saved ähnelt.
        /// </summary>
        internal static string loc_Enter_the_name_under_which_the_favorite_should_be_saved {
            get {
                return ResourceManager.GetString("loc_Enter_the_name_under_which_the_favorite_should_be_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Favorites ähnelt.
        /// </summary>
        internal static string loc_Favorites {
            get {
                return ResourceManager.GetString("loc_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die glue ähnelt.
        /// </summary>
        internal static string loc_glue {
            get {
                return ResourceManager.GetString("loc_glue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Layers ähnelt.
        /// </summary>
        internal static string loc_layers {
            get {
                return ResourceManager.GetString("loc_layers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die lock ähnelt.
        /// </summary>
        internal static string loc_lock {
            get {
                return ResourceManager.GetString("loc_lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        internal static string loc_name {
            get {
                return ResourceManager.GetString("loc_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die print ähnelt.
        /// </summary>
        internal static string loc_print {
            get {
                return ResourceManager.GetString("loc_print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save as favorite ähnelt.
        /// </summary>
        internal static string loc_Save_as_favorite {
            get {
                return ResourceManager.GetString("loc_Save_as_favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save current selection as favourite ähnelt.
        /// </summary>
        internal static string loc_save_current_selection_as_favourite {
            get {
                return ResourceManager.GetString("loc_save_current_selection_as_favourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Favorite ähnelt.
        /// </summary>
        internal static string loc_save_favorites {
            get {
                return ResourceManager.GetString("loc_save_favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set layer properties for all pages ähnelt.
        /// </summary>
        internal static string loc_Set_layer_properties_for_all_pages {
            get {
                return ResourceManager.GetString("loc_Set_layer_properties_for_all_pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string loc_Settings {
            get {
                return ResourceManager.GetString("loc_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die show active column ähnelt.
        /// </summary>
        internal static string loc_show_active_column {
            get {
                return ResourceManager.GetString("loc_show_active_column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die active ähnelt.
        /// </summary>
        internal static string loc_show_fav_active {
            get {
                return ResourceManager.GetString("loc_show_fav_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die glue ähnelt.
        /// </summary>
        internal static string loc_show_fav_glue {
            get {
                return ResourceManager.GetString("loc_show_fav_glue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die lock ähnelt.
        /// </summary>
        internal static string loc_show_fav_lock {
            get {
                return ResourceManager.GetString("loc_show_fav_lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die print ähnelt.
        /// </summary>
        internal static string loc_show_fav_print {
            get {
                return ResourceManager.GetString("loc_show_fav_print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die snap ähnelt.
        /// </summary>
        internal static string loc_show_fav_snap {
            get {
                return ResourceManager.GetString("loc_show_fav_snap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die visible ähnelt.
        /// </summary>
        internal static string loc_show_fav_visible {
            get {
                return ResourceManager.GetString("loc_show_fav_visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die show glue column ähnelt.
        /// </summary>
        internal static string loc_show_glue_column {
            get {
                return ResourceManager.GetString("loc_show_glue_column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Layer Selector ähnelt.
        /// </summary>
        internal static string loc_show_layer_selector {
            get {
                return ResourceManager.GetString("loc_show_layer_selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die show lock column ähnelt.
        /// </summary>
        internal static string loc_show_lock_column {
            get {
                return ResourceManager.GetString("loc_show_lock_column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die show print column ähnelt.
        /// </summary>
        internal static string loc_show_print_column {
            get {
                return ResourceManager.GetString("loc_show_print_column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die show snap column ähnelt.
        /// </summary>
        internal static string loc_show_snap_column {
            get {
                return ResourceManager.GetString("loc_show_snap_column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die show visible column ähnelt.
        /// </summary>
        internal static string loc_show_visible_column {
            get {
                return ResourceManager.GetString("loc_show_visible_column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die snap ähnelt.
        /// </summary>
        internal static string loc_snap {
            get {
                return ResourceManager.GetString("loc_snap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subcategories ähnelt.
        /// </summary>
        internal static string loc_subcategories {
            get {
                return ResourceManager.GetString("loc_subcategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The favorite {0} already exists ähnelt.
        /// </summary>
        internal static string loc_The_favorite_already_exists {
            get {
                return ResourceManager.GetString("loc_The_favorite_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete item ähnelt.
        /// </summary>
        internal static string loc_title_delete {
            get {
                return ResourceManager.GetString("loc_title_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version ähnelt.
        /// </summary>
        internal static string loc_version {
            get {
                return ResourceManager.GetString("loc_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die visible ähnelt.
        /// </summary>
        internal static string loc_visible {
            get {
                return ResourceManager.GetString("loc_visible", resourceCulture);
            }
        }
    }
}
